# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    deps: [build]

  build: cargo build

  run:
    deps: [build]
    env:
      RUST_LOG: info,libcgroups=debug,libcontainer=debug
    cmds:
      - ./target/debug/oci-test

  update:
    desc: Update all dependencies
    cmds:
      - task: update:nix-pkgs
      - task: update:rust-deps

  update:rust-deps:
    desc: Update rust dependencies
    cmds:
      - cargo update

  update:nix-pkgs:
    desc: Update nix flake packages
    cmds:
      - nix flake update
